# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_gameuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameuser',
            unique_together=set([('server_name', 'user_name')]),
        ),
    ]
