# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20170710_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
