# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0005_auto_20170802_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='dojo.Tag'),
        ),
    ]
