# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:08
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0010_auto_20170807_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='dojo/post/%Y/%m/%d'),
        ),
    ]
