# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_lotte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotte',
            name='price',
            field=models.CharField(max_length=300),
        ),
    ]
